import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { careLogService } from './carelog.service';
import { insightsService } from './insights.service';
import type { CareRecipient } from '../types/recipient';
import type { CareLog } from '../types/careLog';

interface ReportOptions {
  recipient: CareRecipient;
  days: number;
  language: 'zh-CN' | 'en';
}

const LABELS: Record<'zh-CN' | 'en', Record<string, string>> = {
  'zh-CN': {
    title: '照护报告',
    recipient: '照护对象',
    period: '时间段',
    days: '天',
    generated: '生成时间',
    summary: '汇总统计',
    totalLogs: '记录总数',
    bathroomVisits: '如厕次数',
    fluidIntake: '总饮水量',
    incontinenceEvents: '失禁事件',
    medicationAdherence: '用药依从性',
    timeline: '详细记录',
    date: '日期',
    time: '时间',
    type: '类型',
    details: '详情',
    notes: '备注',
    bowel: '排便',
    urination: '排尿',
    meal: '饮食',
    medication: '用药',
    mood: '情绪',
    hygiene: '卫生',
    activity: '活动',
    note: '备注',
    medicalConditions: '医疗状况',
    allergies: '过敏信息',
    footer: '本报告由 EverlyCare 生成',
  },
  en: {
    title: 'Care Report',
    recipient: 'Care Recipient',
    period: 'Period',
    days: 'days',
    generated: 'Generated',
    summary: 'Summary',
    totalLogs: 'Total Logs',
    bathroomVisits: 'Bathroom Visits',
    fluidIntake: 'Total Fluid Intake',
    incontinenceEvents: 'Incontinence Events',
    medicationAdherence: 'Medication Adherence',
    timeline: 'Detailed Log',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    details: 'Details',
    notes: 'Notes',
    bowel: 'Bowel',
    urination: 'Urination',
    meal: 'Meal',
    medication: 'Medication',
    mood: 'Mood',
    hygiene: 'Hygiene',
    activity: 'Activity',
    note: 'Note',
    medicalConditions: 'Medical Conditions',
    allergies: 'Allergies',
    footer: 'Generated by EverlyCare',
  },
};

export const reportService = {
  async generateAndSharePdf(options: ReportOptions): Promise<void> {
    const { recipient, days, language } = options;
    const L = LABELS[language];

    // Gather data across the period
    const allLogs: CareLog[] = [];
    let totalFluidMl = 0;
    let bathroomCount = 0;
    let incontinenceCount = 0;

    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days + 1);

    for (let i = 0; i < days; i++) {
      const d = new Date(startDate);
      d.setDate(d.getDate() + i);
      const dateStr = d.toISOString().split('T')[0];
      const logs = await careLogService.getLogs(recipient.id, { date: dateStr });
      allLogs.push(...logs);
    }

    // Calculate summary
    for (const log of allLogs) {
      const data = log.data as any;
      switch (log.logType) {
        case 'bowel':
          bathroomCount++;
          break;
        case 'urination':
          bathroomCount++;
          if (data.isIncontinence) incontinenceCount++;
          break;
        case 'meal':
          if (data.mealType === 'fluid') {
            totalFluidMl += data.fluidAmountMl || 0;
          }
          break;
      }
    }

    const insights = await insightsService.getInsights(recipient.id, days);

    const periodStart = startDate.toLocaleDateString(language);
    const periodEnd = endDate.toLocaleDateString(language);
    const generatedAt = new Date().toLocaleString(language);

    // Sort logs by time descending
    const sortedLogs = [...allLogs].sort(
      (a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime()
    );

    const html = buildHtml({
      L,
      recipient,
      periodStart,
      periodEnd,
      days,
      generatedAt,
      totalLogs: allLogs.length,
      bathroomCount,
      totalFluidMl,
      incontinenceCount,
      medicationAdherence: insights.medicationAdherence,
      logs: sortedLogs,
      language,
    });

    const { uri } = await Print.printToFileAsync({ html, base64: false });

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: L.title,
        UTI: 'com.adobe.pdf',
      });
    }
  },
};

function buildHtml(params: {
  L: Record<string, string>;
  recipient: CareRecipient;
  periodStart: string;
  periodEnd: string;
  days: number;
  generatedAt: string;
  totalLogs: number;
  bathroomCount: number;
  totalFluidMl: number;
  incontinenceCount: number;
  medicationAdherence: number;
  logs: CareLog[];
  language: 'zh-CN' | 'en';
}): string {
  const {
    L,
    recipient,
    periodStart,
    periodEnd,
    days,
    generatedAt,
    totalLogs,
    bathroomCount,
    totalFluidMl,
    incontinenceCount,
    medicationAdherence,
    logs,
    language,
  } = params;

  const logRows = logs
    .map((log) => {
      const date = new Date(log.occurredAt);
      const dateStr = date.toLocaleDateString(language);
      const timeStr = date.toLocaleTimeString(language, {
        hour: '2-digit',
        minute: '2-digit',
      });
      const typeLabel = L[log.logType] || log.logType;
      const details = formatLogDetails(log, L);
      const notes = escapeHtml(log.notes || '');
      return `<tr>
        <td>${dateStr}</td>
        <td>${timeStr}</td>
        <td>${typeLabel}</td>
        <td>${details}</td>
        <td>${notes}</td>
      </tr>`;
    })
    .join('');

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
<meta charset="UTF-8">
<style>
  body {
    font-family: -apple-system, "PingFang SC", "Helvetica Neue", sans-serif;
    color: #2C3E50;
    padding: 40px;
    line-height: 1.6;
  }
  h1 {
    color: #4A90A4;
    border-bottom: 3px solid #4A90A4;
    padding-bottom: 12px;
    margin-bottom: 8px;
  }
  .subtitle {
    color: #7F8C8D;
    font-size: 14px;
    margin-bottom: 24px;
  }
  .meta-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    background: #F8F9FA;
    padding: 16px;
    border-radius: 8px;
    margin-bottom: 24px;
  }
  .meta-label {
    color: #7F8C8D;
    font-size: 12px;
  }
  .meta-value {
    color: #2C3E50;
    font-weight: 600;
  }
  h2 {
    color: #4A90A4;
    font-size: 18px;
    margin-top: 32px;
    margin-bottom: 12px;
  }
  .summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-bottom: 24px;
  }
  .summary-card {
    background: #FFFFFF;
    border: 1px solid #E8EAED;
    border-radius: 8px;
    padding: 16px;
    text-align: center;
  }
  .summary-value {
    font-size: 24px;
    font-weight: 700;
    color: #4A90A4;
  }
  .summary-label {
    font-size: 11px;
    color: #7F8C8D;
    margin-top: 4px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }
  thead th {
    background: #4A90A4;
    color: white;
    padding: 10px 8px;
    text-align: left;
    font-weight: 600;
  }
  tbody td {
    padding: 8px;
    border-bottom: 1px solid #ECEFF1;
  }
  tbody tr:nth-child(even) {
    background: #F8F9FA;
  }
  .footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #E8EAED;
    text-align: center;
    color: #BDC3C7;
    font-size: 11px;
  }
</style>
</head>
<body>
  <h1>${L.title}</h1>
  <div class="subtitle">${L.generated}: ${generatedAt}</div>

  <div class="meta-grid">
    <div>
      <div class="meta-label">${L.recipient}</div>
      <div class="meta-value">${escapeHtml(recipient.name)}</div>
    </div>
    <div>
      <div class="meta-label">${L.period}</div>
      <div class="meta-value">${periodStart} — ${periodEnd} (${days} ${L.days})</div>
    </div>
    ${
      recipient.medicalConditions.length > 0
        ? `<div>
        <div class="meta-label">${L.medicalConditions}</div>
        <div class="meta-value">${recipient.medicalConditions.join(', ')}</div>
      </div>`
        : ''
    }
    ${
      recipient.allergies.length > 0
        ? `<div>
        <div class="meta-label">${L.allergies}</div>
        <div class="meta-value">${recipient.allergies.join(', ')}</div>
      </div>`
        : ''
    }
  </div>

  <h2>${L.summary}</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="summary-value">${totalLogs}</div>
      <div class="summary-label">${L.totalLogs}</div>
    </div>
    <div class="summary-card">
      <div class="summary-value">${bathroomCount}</div>
      <div class="summary-label">${L.bathroomVisits}</div>
    </div>
    <div class="summary-card">
      <div class="summary-value">${totalFluidMl}ml</div>
      <div class="summary-label">${L.fluidIntake}</div>
    </div>
    <div class="summary-card">
      <div class="summary-value">${medicationAdherence}%</div>
      <div class="summary-label">${L.medicationAdherence}</div>
    </div>
  </div>

  <h2>${L.timeline}</h2>
  <table>
    <thead>
      <tr>
        <th>${L.date}</th>
        <th>${L.time}</th>
        <th>${L.type}</th>
        <th>${L.details}</th>
        <th>${L.notes}</th>
      </tr>
    </thead>
    <tbody>
      ${logRows}
    </tbody>
  </table>

  <div class="footer">${L.footer}</div>
</body>
</html>`;
}

function formatLogDetails(log: CareLog, L: Record<string, string>): string {
  const data = log.data as any;
  switch (log.logType) {
    case 'bowel':
      return `${data.type || ''} / ${data.location || ''}${data.isAccident ? ' ⚠' : ''}`;
    case 'urination':
      return `${data.method || ''} / ${data.volume || ''}${data.isIncontinence ? ' ⚠' : ''}`;
    case 'meal':
      if (data.mealType === 'fluid') return `${data.fluidAmountMl || 0}ml`;
      return `${data.mealType || ''}${data.description ? ' — ' + escapeHtml(data.description) : ''}`;
    case 'medication':
      return `${escapeHtml(data.medicationName || '')} / ${data.status || ''}`;
    case 'mood':
      return data.mood || '';
    case 'hygiene':
      return data.type || '';
    case 'activity':
      return `${data.activityType || ''}${
        data.durationMinutes ? ' (' + data.durationMinutes + 'min)' : ''
      }`;
    case 'note':
      return escapeHtml(data.content || '');
    default:
      return '';
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
